### ISSUE TITLE
Merging not working with ecma6 style imports

### ISSUE THREAD

**Issue by sidhujag** [RyuuGan/sol-merger#14]
Hello,

A downstream library which uses sol-merger has issues with using sol-merger because sol-merger does not handle ecma6 style imports. The regex can be simply upgraded and used to fix the problem. See full analysis here:

https://github.com/rkalis/truffle-plugin-verify/issues/4

**Comment by RyuuGan** [comment]
Hello @sidhujag 

The problem here are not just imports that can be done easily, but the main problem is still renaming even if I import:

1. `import {symbol1 as alias, symbol2} from "filename"; ` That can be also done quite easy, just need to assign `alias` to `symbol1`
2. `import "filename" as symbolName;` or `import * as symbolName from "filename";` That is harder. I have to assign a variable `symbolName` that it will have all the functions from file `filename`

If I don't do that the compiled code will be broken because it uses names that are not in the file.

I'll have a look how to solve this and try to do so as soon as possible.

Thanks for the regex and info.

**Comment by sidhujag** [comment]
@RyuuGan thanks makes sense, I should have known that is why hah duh! if you find a solution please let us know here, I will assume for now we will only support simple imports.

**Comment by rkalis** [comment]
I'm running into an issue that I think is related to this. @0xAshish was having difficulty verifying Matic network contracts. After some debugging I think it's related to ECMA6 style imports.

----

See https://github.com/maticnetwork/contracts/blob/mainnet-v1/contracts/root/depositManager/DepositManager.sol for the code.

---

1. `DepositManager` imports `DepositManagerStorage` with ECMA6 style imports. 
2. The `DepositManagerStorage.sol` file includes the contracts `DepositManagerStorage` and `DepositManagerHeader`. 
3. `DepositManagerStorage` extends `DepositManagerHeader`

Since the Storage contract extends the Header contract I would expect both of them to be present in the flattened code. But the Header contract isn't in there, likely because *only* the Storage contract is imported in the main `DepositManager.sol`.

I solved it by changing
```
import {DepositManagerStorage} from "./DepositManagerStorage.sol";
```
to
```
import {DepositManagerStorage, DepositManagerHeader} from "./DepositManagerStorage.sol";
```

---

Do you think there's a way to make this work in sol-merger, or is the solution just to put all contracts in the import statement?

**Comment by sidhujag** [comment]
@rkalis does your version include this code https://github.com/RyuuGan/sol-merger/pull/16

**Comment by rkalis** [comment]
@sidhujag truffle-plugin-verify uses the latest version (3.0.1) of sol-merger, so everything in sol-merger is supported in truffle-plugin-verify.
